### PR TITLE
Use https and update links on home page, faculty page, and positions page

### PR DESCRIPTION
**Pull request by ziyang-theory**
- Update students page with links to personal websites
- Updated theory faculty to remove Henry and Ben
- Update postdoc info
- Update faculty info
- Updated postdocs
- Update student alumni page
- Update postdoc alumni page
- Fix links on the events page and revives the link to Theory Student Seminar
- Use https and update links for home page, faculty page, and positions page

### CODE REVIEW

**Comment by ziyang-theory** [comment]
Screen Shot 2023-05-14 at 16 43 10

Home page: links to department website, UofT, and DCS employment page are updated to the newest links. Nothing else is changed.

**Comment by ziyang-theory** [comment]
Screen Shot 2023-05-14 at 16 47 22
Screen Shot 2023-05-14 at 16 47 25

Faculty page, the only thing changed are replacing 'http' with 'https'. I have tested all https links and they are all working.

**Comment by ziyang-theory** [comment]
Screen Shot 2023-05-14 at 16 47 35

Positions page: updated the link to the DCS website. That's the only thing changed.

**Comment by sachdevasushant** [comment]
Thank you very much, Ziyang!

**Pull request merged**
